### ISSUE TITLE
师傅加载不起来，可以提供一个测试的c#或者dll吗

### ISSUE THREAD

**Issue by m0s30** [wat4r/GodzillaAssemblyLoadPlugin#1]
插件运行
![image](https://github.com/wat4r/GodzillaAssemblyLoadPlugin/assets/54650671/989248af-6250-4068-a131-10a972fa173a)

测试代码
![image](https://github.com/wat4r/GodzillaAssemblyLoadPlugin/assets/54650671/f2393b8e-201d-458d-af17-016cc564d26b)

**Comment by wat4r** [comment]
dll代码和使用方式没有错误，请检查以下内容：
 - 编译dll的c#版本
 - 编译dll的架构和站点运行的架构是否相同（x84/x64）
